services:
  postgresdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: hello@world#123
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data 